""".. include:: ../README.md

.. attention:: This is ...
.. caution:: This is ...
.. danger:: This is ...
.. error:: This is ...
.. hint:: This is ...
.. important:: This is ...
.. note:: This is ...
.. tip:: This is ...
.. warning:: This is ...
.. admonition:: Title ...

   You can make up your own admonition too.

.. versionadded::

.. versionchanged::

.. deprecated::

.. todo::
"""
